# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: K_means.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rK_means.proto\x12\x06kmeans\"Z\n\nMapRequest\x12\x16\n\x0einput_location\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x01(\t\x12\x11\n\tcentroids\x18\x03 \x03(\t\x12\x12\n\nn_reducers\x18\x04 \x01(\x05\"\x81\x01\n\x0bMapResponse\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.kmeans.MapResponse.Status\x12\"\n\x1aintermediate_file_location\x18\x02 \x03(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\"P\n\rReduceRequest\x12\x0e\n\x06points\x18\x01 \x03(\t\x12#\n\x1bintermediate_file_locations\x18\x02 \x03(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\x90\x01\n\x0eReduceResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.kmeans.ReduceResponse.Status\x12\x18\n\x10output_file_path\x18\x02 \x01(\t\x12\x11\n\tcentroids\x18\x03 \x03(\t\"\"\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32?\n\rMapperService\x12.\n\x03Map\x12\x12.kmeans.MapRequest\x1a\x13.kmeans.MapResponse2I\n\x0eReducerService\x12\x37\n\x06Reduce\x12\x15.kmeans.ReduceRequest\x1a\x16.kmeans.ReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'K_means_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=25
  _globals['_MAPREQUEST']._serialized_end=115
  _globals['_MAPRESPONSE']._serialized_start=118
  _globals['_MAPRESPONSE']._serialized_end=247
  _globals['_MAPRESPONSE_STATUS']._serialized_start=213
  _globals['_MAPRESPONSE_STATUS']._serialized_end=247
  _globals['_REDUCEREQUEST']._serialized_start=249
  _globals['_REDUCEREQUEST']._serialized_end=329
  _globals['_REDUCERESPONSE']._serialized_start=332
  _globals['_REDUCERESPONSE']._serialized_end=476
  _globals['_REDUCERESPONSE_STATUS']._serialized_start=213
  _globals['_REDUCERESPONSE_STATUS']._serialized_end=247
  _globals['_MAPPERSERVICE']._serialized_start=478
  _globals['_MAPPERSERVICE']._serialized_end=541
  _globals['_REDUCERSERVICE']._serialized_start=543
  _globals['_REDUCERSERVICE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
